version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3307"
  web:
    build:
      context: .
      dockerfile: API_Playlist/Dockerfile/Dockerfile
    command: python3 run.py
    volumes:
      - .:/API_Playlist
    ports:
      - "5000:5000"
  web_2:
    build:
      context: .
      dockerfile: API_Cervejas/Dockerfile/Dockerfile
    command: python3 run.py
    volumes:
      - .:/API_Cervejas
    ports:
      - "4444:4444"
    depends_on:
      - db
